In [2]:
# Imports
import pandas as pd
from pathlib import Path
import numpy as np

In [3]:
# Globais
DADOS_CRIMES = r".\dadosPlanilha\BancoVDE 2025.xlsx"
DADOS_POP = r"./dadosPlanilha/ibge/br_ibge_populacao_municipio.csv"
DADOS_ID = r"./dadosPlanilha/ibge/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.ods"
ANO = 2025

In [4]:
df_popAnual = pd.read_csv(DADOS_POP)
df_popAnual.head(3)

    ano sigla_uf  id_municipio  populacao
0  1991       RO     1100015.0    31981.0
1  1991       RO     1100023.0    83684.0
2  1991       RO     1100031.0     8173.0

In [5]:
df_ids = pd.read_excel(DADOS_ID)
df_ids.head(3)

,UF,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Unnamed: 9
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,NaN
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,379,1100379,Alto Alegre dos Parecis,NaN
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,403,1100403,Alto Paraíso,NaN

In [6]:
df_ids = df_ids.drop([
    'Região Geográfica Intermediária',
    'Nome Região Geográfica Intermediária',
    'Região Geográfica Imediata',
    'Nome Região Geográfica Imediata',
    'Município',
    'Unnamed: 9'
    ], axis= 1)
df_ids.head(1)

   UF   Nome_UF  Código Município Completo         Nome_Município
0  11  Rondônia                    1100015  Alta Floresta D'Oeste

In [7]:
import pandas as pd

dicionario_estados = {
    'Acre': 'AC',
    'Alagoas': 'AL',
    'Amapá': 'AP',
    'Amazonas': 'AM',
    'Bahia': 'BA',
    'Ceará': 'CE',
    'Distrito Federal': 'DF',
    'Espírito Santo': 'ES',
    'Goiás': 'GO',
    'Maranhão': 'MA',
    'Mato Grosso': 'MT',
    'Mato Grosso do Sul': 'MS',
    'Minas Gerais': 'MG',
    'Pará': 'PA',
    'Paraíba': 'PB',
    'Paraná': 'PR',
    'Pernambuco': 'PE',
    'Piauí': 'PI',
    'Rio de Janeiro': 'RJ',
    'Rio Grande do Norte': 'RN',
    'Rio Grande do Sul': 'RS',
    'Rondônia': 'RO',
    'Roraima': 'RR',
    'Santa Catarina': 'SC',
    'São Paulo': 'SP',
    'Sergipe': 'SE',
    'Tocantins': 'TO'
}

df_ids['UF_Sigla'] = df_ids['Nome_UF'].map(dicionario_estados)
df_ids.head(10)

   UF   Nome_UF  Código Município Completo           Nome_Município UF_Sigla
0  11  Rondônia                    1100015    Alta Floresta D'Oeste       RO
1  11  Rondônia                    1100379  Alto Alegre dos Parecis       RO
2  11  Rondônia                    1100403             Alto Paraíso       RO
3  11  Rondônia                    1100346         Alvorada D'Oeste       RO
4  11  Rondônia                    1100023                Ariquemes       RO
5  11  Rondônia                    1100452                  Buritis       RO
6  11  Rondônia                    1100031                   Cabixi       RO
7  11  Rondônia                    1100601              Cacaulândia       RO
8  11  Rondônia                    1100049                   Cacoal       RO
9  11  Rondônia                    1100700   Campo Novo de Rondônia       RO

In [8]:
df_ids = df_ids.drop(['UF','Nome_UF'], axis=1)
df_ids.head(3)

   Código Município Completo           Nome_Município UF_Sigla
0                    1100015    Alta Floresta D'Oeste       RO
1                    1100379  Alto Alegre dos Parecis       RO
2                    1100403             Alto Paraíso       RO

In [9]:
np.unique(df_ids['UF_Sigla'])

array(['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG',
       'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR',
       'RS', 'SC', 'SE', 'SP', 'TO'], dtype=object)

In [10]:
df_completo = pd.read_excel(DADOS_CRIMES)
df_completo.head()

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [11]:
df = df_completo

In [12]:
df = df[~df['evento'].isin(['Morte de Agente do Estado', 'Suicídio de Agente do Estado'])].drop(['agente'], axis=1)
df.head()

,uf,municipio,evento,data_referencia,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [13]:
df = df[~df['evento'].isin(['Arma de Fogo Apreendida'])].drop(['arma'], axis=1)
df.head()

,uf,municipio,evento,data_referencia,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [14]:
df = df[~df['evento'].isin(['Pessoa Desaparecida', 'Pessoa Localizada'])].drop(['faixa_etaria'], axis=1)
df.head()

,uf,municipio,evento,data_referencia,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [15]:
df = df[~df['evento'].isin(['Apreensão de Cocaína', 'Apreensão de Maconha'])].drop(['total_peso'], axis=1)
df.head()

,uf,municipio,evento,data_referencia,feminino,masculino,nao_informado,total_vitima,total,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,0.0,0.0,0.0,0.0,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,0.0,0.0,0.0,0.0,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,0.0,0.0,0.0,0.0,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,0.0,0.0,0.0,0.0,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,0.0,0.0,0.0,0.0,NaN,Estadual

In [16]:
df = df[~df['evento'].isin([
    'Atendimento pré-hospitalar',
    'Busca e salvamento',
    'Combate a incêndios',
    'Emissão de Alvarás de licença',
    'Mandado de prisão cumprido',
    'Mortes a esclarecer (sem indício de crime)',
    'Realização de vistorias'
])]
df.head()

,uf,municipio,evento,data_referencia,feminino,masculino,nao_informado,total_vitima,total,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,0.0,0.0,0.0,0.0,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,0.0,0.0,0.0,0.0,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,0.0,0.0,0.0,0.0,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,0.0,0.0,0.0,0.0,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,0.0,0.0,0.0,0.0,NaN,Estadual

In [17]:
df = df[~df['municipio'].isin(['NÃO INFORMADO'])]
df.head()

,uf,municipio,evento,data_referencia,feminino,masculino,nao_informado,total_vitima,total,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,0.0,0.0,0.0,0.0,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,0.0,0.0,0.0,0.0,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,0.0,0.0,0.0,0.0,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,0.0,0.0,0.0,0.0,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,0.0,0.0,0.0,0.0,NaN,Estadual

In [18]:
eventos_alvo = [
    'Furto de veículo', 
    'Roubo a instituição financeira', 
    'Roubo de carga', 
    'Roubo de veículo', 
    'Tráfico de drogas'
]

df_alvo = df[df['evento'].isin(eventos_alvo)]
df_outros = df[~df['evento'].isin(eventos_alvo)]

colunas_chave = ['uf', 'municipio', 'evento', 'data_referencia']
colunas_soma = ['feminino', 'masculino', 'nao_informado', 'total_vitima', 'total']

df_consolidado = df_alvo.groupby(colunas_chave, as_index=False, dropna=False)[colunas_soma].sum(min_count=1)

df_consolidado['abrangencia'] = 'combo'
df = pd.concat([df_outros, df_consolidado], ignore_index=True)

df

,uf,municipio,evento,data_referencia,feminino,masculino,nao_informado,total_vitima,total,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,0.0,0.0,0.0,0.0,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,2025-02-01,0.0,0.0,0.0,0.0,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,2025-03-01,0.0,0.0,0.0,0.0,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,2025-04-01,0.0,0.0,0.0,0.0,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,2025-05-01,0.0,0.0,0.0,0.0,NaN,Estadual
...,...,...,...,...,...,...,...,...,...,...
605011,TO,XAMBIOÁ,Tentativa de homicídio,2025-08-01,0.0,3.0,0.0,3.0,NaN,Estadual
605012,TO,XAMBIOÁ,Tentativa de homicídio,2025-09-01,0.0,0.0,0.0,0.0,NaN,Estadual
605013,TO,XAMBIOÁ,Tentativa de homicídio,2025-10-01,0.0,0.0,0.0,0.0,NaN,Estadual
605014,TO,XAMBIOÁ,Tentativa de homicídio,2025-11-01,0.0,0.0,0.0,0.0,NaN,Estadual
605015,TO,XAMBIOÁ,Tentativa de homicídio,2025-12-01,0.0,0.0,0.0,0.0,NaN,Estadual

In [19]:
df = df.drop(['total'], axis=1)
df.head(1)

,uf,municipio,evento,data_referencia,feminino,masculino,nao_informado,total_vitima,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,2025-01-01,0.0,0.0,0.0,0.0,Estadual

In [20]:
df = df.drop(['feminino'], axis=1).drop(['masculino'], axis=1).drop(['nao_informado'], axis=1)
df.head(10)

   uf   municipio       evento data_referencia  total_vitima abrangencia
0  AC  ACRELÂNDIA  Feminicídio      2025-01-01           0.0    Estadual
1  AC  ACRELÂNDIA  Feminicídio      2025-02-01           0.0    Estadual
2  AC  ACRELÂNDIA  Feminicídio      2025-03-01           0.0    Estadual
3  AC  ACRELÂNDIA  Feminicídio      2025-04-01           0.0    Estadual
4  AC  ACRELÂNDIA  Feminicídio      2025-05-01           0.0    Estadual
5  AC  ACRELÂNDIA  Feminicídio      2025-06-01           0.0    Estadual
6  AC  ACRELÂNDIA  Feminicídio      2025-07-01           0.0    Estadual
7  AC  ACRELÂNDIA  Feminicídio      2025-08-01           0.0    Estadual
8  AC  ACRELÂNDIA  Feminicídio      2025-09-01           0.0    Estadual
9  AC  ACRELÂNDIA  Feminicídio      2025-10-01           0.0    Estadual

In [21]:
df['data_referencia'] = pd.to_datetime(df['data_referencia'])

df['ano'] = df['data_referencia'].dt.year
df['mes'] = df['data_referencia'].dt.month
df = df.drop(['data_referencia'], axis=1)

df.head(1)

   uf   municipio       evento  total_vitima abrangencia   ano  mes
0  AC  ACRELÂNDIA  Feminicídio           0.0    Estadual  2025    1

In [22]:
def padronizar_texto(coluna):
    return coluna.str.normalize('NFKD') \
                 .str.encode('ascii', errors='ignore') \
                 .str.decode('utf-8') \
                 .str.upper() \
                 .str.strip() 

df['chave_mun'] = padronizar_texto(df['municipio'])
df['chave_uf'] = padronizar_texto(df['uf'])

df_ids['chave_mun'] = padronizar_texto(df_ids['Nome_Município'])
df_ids['chave_uf'] = padronizar_texto(df_ids['UF_Sigla'])

df = df.merge(
    df_ids[['Código Município Completo', 'chave_mun', 'chave_uf']], 
    on=['chave_uf', 'chave_mun'],
    how='left'
)

df = df.rename(columns={'Código Município Completo': 'Cod_municipio'})
df = df.drop(columns=['chave_mun', 'chave_uf'])
df.head()

,uf,municipio,evento,total_vitima,abrangencia,ano,mes,Cod_municipio
0,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,1,1200013.0
1,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,2,1200013.0
2,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,3,1200013.0
3,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,4,1200013.0
4,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,5,1200013.0

In [23]:
df = df.merge(
    df_popAnual[['id_municipio', 'ano', 'populacao']],
    left_on=['Cod_municipio', 'ano'],
    right_on=['id_municipio', 'ano'],
    how='left'
)

df = df.drop(columns=['id_municipio'])
df.head()

,uf,municipio,evento,total_vitima,abrangencia,ano,mes,Cod_municipio,populacao
0,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,1,1200013.0,14712.0
1,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,2,1200013.0,14712.0
2,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,3,1200013.0,14712.0
3,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,4,1200013.0,14712.0
4,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,5,1200013.0,14712.0

In [24]:
df['vitimas_escala'] = (df['total_vitima'] / df['populacao']) * 100000
df.head()

,uf,municipio,evento,total_vitima,abrangencia,ano,mes,Cod_municipio,populacao,vitimas_escala
0,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,1,1200013.0,14712.0,0.0
1,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,2,1200013.0,14712.0,0.0
2,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,3,1200013.0,14712.0,0.0
3,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,4,1200013.0,14712.0,0.0
4,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,5,1200013.0,14712.0,0.0

In [25]:
mapeamento_crimes = {
    'Feminicídio': 1,
    'Homicídio doloso': 2,
    'Lesão corporal seguida de morte': 3,
    'Morte no trânsito ou em decorrência dele (exceto homicídio doloso)': 4,
    'Mortes no trânsito': 5,
    'Roubo seguido de morte (latrocínio)': 6,
    'Suicídio': 7,
    'Tentativa de feminicídio': 8,
    'Tentativa de homicídio': 9
}

df['crime_enum'] = df['evento'].map(mapeamento_crimes)
print(df[['evento', 'crime_enum']].head())

        evento  crime_enum
0  Feminicídio           1
1  Feminicídio           1
2  Feminicídio           1
3  Feminicídio           1
4  Feminicídio           1

In [27]:
df.head()

,uf,municipio,evento,total_vitima,abrangencia,ano,mes,Cod_municipio,populacao,vitimas_escala,crime_enum
0,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,1,1200013.0,14712.0,0.0,1
1,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,2,1200013.0,14712.0,0.0,1
2,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,3,1200013.0,14712.0,0.0,1
3,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,4,1200013.0,14712.0,0.0,1
4,AC,ACRELÂNDIA,Feminicídio,0.0,Estadual,2025,5,1200013.0,14712.0,0.0,1

In [29]:
df.drop(['evento','total_vitima','abrangencia','Cod_municipio','populacao'], axis=1).to_csv(
    r'./dadosTratados/dados_crimes_2025.csv', 
    index=False
)